plugins { id 'com.android.application' }

android {
    namespace 'com.yosef.konkaremote'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yosef.konkaremote'
        minSdk 23
        targetSdk 35
        versionCode 10
        versionName '1.2.1'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
